apiVersion: apps/v1
kind: Deployment
metadata:
  name: feeder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feeder
  template:
    metadata:
      labels:
        app: feeder
    spec:
      containers:
      - name: feeder
        image: nixery.dev/shell/curl/jq/bc
        env:
          - name: FRESH_START
            value: "false"
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        command:
          - sh
        args:
          - -c
          - |
            set -o nounset
            #set -x
            _sec=45
            [ "x${FRESH_START}" = "xtrue" ] && {
              echo "resetting the models"
              for svc in 15m 30m 60m 120m sum-all sum-some; do
                curl -s -X DELETE http://keda-prophet.default.svc:8000/models/minute-metrics-${svc}
              done
            }

            while true; do
              _sumAll=0
              _sumSome=0
              time=$(date -u +"%Y-%m-%d %H:%M:%S")
              (
                for svc in 15m 30m 60m 120m; do
                  value=$(curl -s http://minute-metrics-${svc}.default.svc/api/v1/minutemetrics | jq '.value')
                  if [ $? -eq 0 ]; then
                    _sumAll=$(echo "$_sumAll + $value" | bc)
                    [[ "${svc}" = "15m" || "${svc}" = "120m" ]] && _sumSome=$(echo "$_sumSome + $value" | bc)
                    echo -e "\n - At ${time} for minute-metrics-${svc} got: ${value}"
                    curl -s -X POST http://keda-prophet.default.svc:8000/models/minute-metrics-${svc}/metrics \
                      -H "Content-Type: application/json" \
                      -d "{
                        \"date\": \"${time}\",
                        \"value\": ${value}
                      }" | jq '.message'
                  else
                    echo "Unable to get value from http://minute-metrics-${svc}.default.svc/api/v1/minutemetrics"
                  fi
                done
                echo -e "\n - At ${time} for minute-metrics-sum-all got: ${_sumAll}"
                curl -s -X POST http://keda-prophet.default.svc:8000/models/minute-metrics-sum-all/metrics \
                      -H "Content-Type: application/json" \
                      -d "{
                        \"date\": \"${time}\",
                        \"value\": ${_sumAll}
                      }" | jq '.message'
                echo -e "\n - At ${time} for minute-metrics-sum-some (15m + 120m) got: ${_sumSome}"
                curl -s -X POST http://keda-prophet.default.svc:8000/models/minute-metrics-sum-some/metrics \
                      -H "Content-Type: application/json" \
                      -d "{
                        \"date\": \"${time}\",
                        \"value\": ${_sumSome}
                      }" | jq '.message'
              )&
              echo -e "\n\nWaiting ${_sec} seconds.."
              sleep ${_sec}
            done
            exit 1
---
