apiVersion: apps/v1
kind: Deployment
metadata:
  name: minute-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minute-metrics
  template:
    metadata:
      labels:
        app: minute-metrics
    spec:
      containers:
      - name: minute-metrics
        # arm only, todo: rights for ghcr.io/kedify/sample-minute-metrics img
        image: docker.io/jkremser/sample-minute-metrics:cycles
        ports:
        - containerPort: 8080
        env:
        - name: CYCLE_MINUTES
          value: "30"
        - name: SCHEDULE
          # value goes from 0 to 15 then back to 0 in 30 min cycles
          value: "0:0,1:1,2:2,3:3,4:4,5:5,6:6,7:7,8:8,9:9,10:10,11:11,12:12,13:13,14:14,15:15,16:14,17:13,18:12,19:11,20:10,21:9,22:8,23:7,24:6,25:5,26:4,27:3,28:2,29:1"
---
apiVersion: v1
kind: Service
metadata:
  name: minute-metrics
spec:
  selector:
    app: minute-metrics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
