apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keda-prophet.fullname" . }}
  labels:
    {{- include "keda-prophet.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keda-prophet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keda-prophet.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: keda-prophet
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: DB_FILE
              value: {{ .Values.settings.storage.dbFile }}
            - name: MODELS_PATH
              value: {{ .Values.settings.storage.modelsPath }}
          args:
            - --log-level={{ .Values.settings.logs.logLvl }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.kedaPredictionController.enabled }}
        - name: prediction-controller
          image: {{ .Values.kedaPredictionController.image.repository }}:{{ .Values.kedaPredictionController.image.tag }}
          imagePullPolicy: {{ .Values.kedaPredictionController.image.pullPolicy }}
          args:
            - --keda-metrics-cert-path=/etc/tls
            - --keda-metrics-address={{ .Values.kedaPredictionController.kedaMetricsAddress }}
            - --keda-prophet-address=:8000
            - --internal-metrics-bind-address=:8081
          volumeMounts:
            - name: certs
              mountPath: /etc/tls
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
        {{- end }}
        {{- with .Values.extraContainers }}
          {{- tpl . $ | nindent 8 }}
        {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.kedaPredictionController.enabled }}
        - name: certs
          secret:
            defaultMode: 420
            secretName: kedaorg-certs
      {{- end }}
      {{- with .Values.nodeSelector }}
      {{- if .Values.kedaPredictionController.enabled }}
      serviceAccountName: {{ include "keda-prophet.fullname" . }}
      {{- end }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
