apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keda-prophet.fullname" . }}
  labels:
    {{- include "keda-prophet.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keda-prophet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keda-prophet.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.kedaPredictionController.enabled }}
      initContainers:
        {{- include "prophet.container" . | nindent 8 }}
      {{- end }}
      containers:
        {{- if not .Values.kedaPredictionController.enabled }}
        {{- include "prophet.container" . | nindent 8 }}
        {{- else }}
        - name: prediction-controller
          image: {{ .Values.kedaPredictionController.image.repository }}:{{ .Values.kedaPredictionController.image.tag }}
          imagePullPolicy: {{ .Values.kedaPredictionController.image.pullPolicy }}
          args:
            - --keda-metrics-cert-path=/etc/tls
            - --keda-metrics-address={{ .Values.kedaPredictionController.kedaMetricsAddress }}
            - --keda-prophet-address=:8000
            - --internal-metrics-bind-address=:8081
            - --zap-log-level={{ .Values.settings.logs.logLvl }}
            - --zap-stacktrace-level={{ .Values.settings.logs.stackTracesLvl }}
          volumeMounts:
            - name: certs
              mountPath: /etc/tls
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
        {{- end }}
        {{- with .Values.extraContainers }}
          {{- tpl . $ | nindent 8 }}
        {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.kedaPredictionController.enabled }}
        - name: certs
          secret:
            defaultMode: 420
            secretName: kedaorg-certs
      {{- end }}
      
      {{- if .Values.kedaPredictionController.enabled }}
      serviceAccount: {{ include "keda-prophet.fullname" . }}
      {{- end -}}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end -}}
      
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end -}}
      
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end -}}
